version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
  orderdb:
    image: mcr.microsoft.com/mssql/server:latest
  catalogdb:
    image: mongo 
  basketdb:
    image: redis:alpine
  discountdb:
    image: postgres

  pgadmin:
    image: dpage/pgadmin4
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Catalog.Api/Dockerfile
  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Basket.Api/Dockerfile

  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: Discount.Api/Dockerfile

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Discount.Grpc/Dockerfile

  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Ordering.Api/Dockerfile

volumes:
  mongo_data:
  postgres_data:
  pgadmin_data:



